### ISSUE TITLE
CompileError in Chrome 69

### ISSUE THREAD

**Issue by eranimo** [Markyparky56/WasmNoise#6]
I got the following error when running v0.4.2:
```
CompileError: AsyncCompile: Wasm decoding failed: expected magic word 00 61 73 6d, found 76 61 72 20 @+0
```

**Comment by Markyparky56** [comment]
Hi, can you tell me a little more about how you're working with WasmNoise? Did you use the release zip or compioe from source? Are you using the autoloader.js script? 

From what I can tell right now, that kind of compile error occurs when you try and compile a text file rather than the wasm binary.

**Comment by eranimo** [comment]
I used the v0.4.2 release `.wasm` file. I didn't try compiling it from source because it looked quite complicated and I'm new to WebAssembly.

**Comment by Markyparky56** [comment]
No worries, compiling from source can be a lot of work. I'd like to set up a nice script which sets up the build pipeline, but I don't have that much time to work on it right now. 

If you could post the code you're working with that would make troubleshooting a lot easier.

I've uploaded an updated version of the autoloader and a new v0.4.3 binary (which is working for me in Chrome 69.0.3497.100). 

Are you using the `wasmnoise.autoloader.js` script? It handles all the setup and creates a nice WasmNoise object which you can call the functions through (plus it has lots of lovely helper functions which grab the values generated by the bulk functions out of memory for you). If that's not working for you then we've got a problem.

I'd recommend cloning the repository just so you can get a copy of the test html files, or at least try running the autoloadertest.html page:
``` html
<html>
  <head>
    <script type="text/javascript" src="./wasmnoise.autoloader.js"></script>
    <script type="text/javascript">
      // Optional onLoaded function callback
      WasmNoise.onLoaded = function()
      {
        document.getElementById("loaded").innerText = "Loaded!";
      }
    </script>
  </head>
  <body>
    <span id="loaded">Loading...</span>
    <script>
      function update()
      {
        if(WasmNoise) 
          if(WasmNoise.loaded) 
            console.log(WasmNoise.GetSimplex2(Math.random(), Math.random()));
      }
      setInterval(() => {update()}, 1000);
    </script>
  </body>
</html>
```

**Comment by Markyparky56** [comment]
Closing as you haven't raised any further problems.
